# Generated by Django 4.2.7 on 2023-12-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('slug', models.CharField(max_length=255)),
                ('content', models.TextField(verbose_name='Cодержимое')),
                ('preview', models.ImageField(upload_to='preview/', verbose_name='Превью статьи')),
                ('date_of_creation', models.DateTimeField(verbose_name='Дата создания')),
                ('is_published', models.BooleanField(verbose_name='Признак публикации')),
                ('count_of_view', models.IntegerField(verbose_name='Количество просмотров')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
