# Generated by Django 4.2.7 on 2023-12-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='count_of_view',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
