# Generated by Django 4.2.7 on 2023-11-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.CharField(max_length=255, verbose_name='описание')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение')),
                ('catgory', models.CharField(max_length=100, verbose_name='категория')),
                ('price', models.IntegerField(verbose_name='цена за штуку')),
                ('date_of_creation', models.DateField(max_length=100, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(max_length=100, verbose_name='дата изменения')),
            ],
        ),
    ]
