# Generated by Django 4.2.7 on 2023-12-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='number_of_version',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер версии'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='version',
            name='title_of_version',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Название версии'),
        ),
    ]
